name: Solicitação de Funcionalidade
description: Sugira uma nova funcionalidade ou melhoria
title: "[FEATURE]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! Preencha o formulário abaixo para descrever sua ideia.

  - type: input
    id: contexto
    attributes:
      label: Contexto ou Problema
      description: Qual problema você está tentando resolver?
      placeholder: "Ex: É difícil encontrar itens na lista porque não há filtro."
    validations:
      required: true

  - type: textarea
    id: proposta
    attributes:
      label: Sua Proposta
      description: Descreva a funcionalidade que gostaria de ver implementada.
      placeholder: "Ex: Adicionar um campo de busca no topo da lista de itens."
    validations:
      required: true

  - type: textarea
    id: beneficios
    attributes:
      label: Benefícios
      description: Como essa funcionalidade melhoraria o projeto?
      placeholder: "Ex: Vai melhorar a usabilidade e reduzir o tempo de busca."
    validations:
      required: false

  - type: checkboxes
    id: termos
    attributes:
      label: Confirmação
      options:
        - label: Verifiquei se esta funcionalidade já foi solicitada anteriormente.
          required: true

