site_name: Apresentação Docker/Kubernetes
theme: readthedocs
nav:
  - Virtualização "O INÍCIO": 01-inicio.md
  - Virtual Machine: 02-vms.md
  - Containers: 03-containers.md
  - Principais diferenças: 04-diferencas.md
  - Docker: 05-docker.md
  - Kubernetes: 06-kubernetes.md
  - Openshift: 07-openshift.md
