site_name: Docker / Kubernetes
theme: readthedocs
nav:
  - Home: index.md
  - Slide 1 - Apresentacao sobre docker e kubernetes: slide1.md
  - Slide 2 - Maquinas virtuais x Containers: slide2.md
  - Slide 3 - Vantagens e desvantagens de cada um: slide3.md
  - Slide 4 - Diferentes ambientes de aplicações: slide4.md
  - Slide 5 - Gráfico DATADOG: slide5.md
  - Slide 6 - Adoção de containers: slide6.md
  - Slide 7 - Docker: slide7.md
  - Slide 8 - Comandos do Dockerfile: slide8.md
  - Slide 9 - Exemplos de Dockerfile: slide9.md
  - Slide 10 - Comandos básicos docker: slide10.md
  - Slide 11 - Criando imagem docker: slide11.md
  - Slide 12 - Kubernetes: slide12.md
  - Slide 13 - O que é kubernetes: slide13.md
  - Slide 14 - Infraestrutura mínima: slide14.md
  - Slide 15 - Kubernetes: slide15.md
